// This file is automatically generated by the Supabase CLI in some setups.
// It's OK to edit it if needed for your project.

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment variables (set in .env / GitHub Actions secrets)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

// Import the supabase client like this:
//   import { supabase } from '@/integrations/supabase/client';

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      // Persist session across reloads
      persistSession: true,
      // Automatically refresh the access token
      autoRefreshToken: true,
      // IMPORTANT: process OAuth tokens from the URL after Google redirect
      detectSessionInUrl: true,
    },
  }
);
